version: '2.4'

services:
  cassandra-1: &cassandra_base
    image: cassandra:3.11
    ports:
      - "${cassandra_ip_port:-127.0.0.1:9042-9044}:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra-1
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 3s
      timeout: 2s
      retries: 60
  cassandra-2:
    <<: *cassandra_base
    depends_on:
      cassandra-1:
        condition: service_healthy
  cassandra-3:
    <<: *cassandra_base
    depends_on:
      cassandra-2:
        condition: service_healthy

  server:
    build:
      context: ./docker-sbt
      args:
        - http_proxy
        - https_proxy
    volumes:
      # ホストのsbtのcacheを共有するならば環境変数でpathを指定
      - ${ivy_cache_dir:-ivy-cache}:/root/.ivy2
      - ${sbt_cache_dir:-sbt-cache}:/root/.sbt
      # ソースをホストと共有
      - ./server:/app
      # targetはホストと共有しない
      - /app/target
      - /app/project/target
    ports:
      - "${server_ip_port:-127.0.0.1:8080}:8080"
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra-1,cassandra-2,cassandra-3
      - http_proxy
      - https_proxy
    command: >
      sbt
      -Dhttp.interface=0.0.0.0
      -Dcassandra-journal.replication-factor=3
      run
    tty: true

volumes:
  ivy-cache:
  sbt-cache:
