version: '3'

services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "${cassandra_ip_port:-127.0.0.1:9042}:9042"

  server:
    build:
      context: ./docker-sbt
      args:
        - http_proxy
        - https_proxy
    volumes:
      # ホストのsbtのcacheを共有するならば環境変数でpathを指定
      - ${ivy_cache_dir:-ivy-cache}:/root/.ivy2
      - ${sbt_cache_dir:-sbt-cache}:/root/.sbt
      # ソースをホストと共有
      - ./server:/app
      # targetはホストと共有しない
      - /app/target
      - /app/project/target
    ports:
      - "${server_ip_port:-127.0.0.1:8080}:8080"
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra
      - http_proxy
      - https_proxy
    command: >
      sbt
      -Dhttp.interface=0.0.0.0
      run
    tty: true

volumes:
  ivy-cache:
  sbt-cache:
